# Generated by Django 4.1.4 on 2023-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='name',
            field=models.CharField(max_length=199, unique=True),
        ),
    ]
