# Generated by Django 4.2.1 on 2023-06-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_mng', '0001_initial'),
        ('opportunity_mng', '0002_rename_risk_opportunity'),
        ('risk_mng', '0001_initial'),
        ('process_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessToRisks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_mng.process')),
                ('risk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_mng.risk')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessToOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity_mng.opportunity')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_mng.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessToKpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_mng.kpi')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_mng.process')),
            ],
        ),
    ]
