# Generated by Django 4.1.4 on 2023-01-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0002_alter_document_slug'),
        ('process_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='documents',
            field=models.ManyToManyField(blank=True, through='process_mng.ProcessStepToDocuments', to='dox_mng.document'),
        ),
    ]
