# Generated by Django 4.2.1 on 2023-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_mng', '0002_rename_risk_opportunity'),
        ('kpi_mng', '0001_initial'),
        ('risk_mng', '0001_initial'),
        ('process_mng', '0002_processtorisks_processtoopportunities_processtokpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='kpis',
            field=models.ManyToManyField(blank=True, through='process_mng.ProcessToKpis', to='kpi_mng.kpi'),
        ),
        migrations.AddField(
            model_name='process',
            name='opportunities',
            field=models.ManyToManyField(blank=True, through='process_mng.ProcessToOpportunities', to='opportunity_mng.opportunity'),
        ),
        migrations.AddField(
            model_name='process',
            name='risks',
            field=models.ManyToManyField(blank=True, through='process_mng.ProcessToRisks', to='risk_mng.risk'),
        ),
    ]
