# Generated by Django 4.1.4 on 2023-01-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0002_alter_processstep_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.CharField(choices=[('Managerial', 'Managerial'), ('Operational', 'Operational'), ('Support', 'Support')], max_length=30),
        ),
    ]
