# Generated by Django 4.1.4 on 2023-02-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0003_process_process_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
