# Generated by Django 4.2.1 on 2023-07-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0003_alter_employee_position_and_more'),
        ('process_mng', '0003_process_kpis_process_opportunities_process_risks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_owner',
            field=models.ForeignKey(db_column='responsible_ident', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mng.employee', to_field='identification'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='parent_process',
            field=models.ForeignKey(db_column='parent_process_number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_mng.process', to_field='number'),
        ),
    ]
