# Generated by Django 4.1.4 on 2023-01-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0003_alter_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
