# Generated by Django 4.1.4 on 2023-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0004_alter_process_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
