# Generated by Django 4.1.4 on 2023-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0006_alter_process_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
