# Generated by Django 4.1.4 on 2023-01-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0008_alter_processstep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
