# Generated by Django 4.1.4 on 2023-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0009_processstep_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=99, unique=True),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='name',
            field=models.CharField(max_length=99, unique=True),
        ),
    ]
