# Generated by Django 4.2.1 on 2023-06-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0001_initial'),
        ('newactions_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaction',
            name='responsible',
            field=models.ForeignKey(db_column='owner_ident', on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='hr_mng.employee', to_field='identification'),
        ),
    ]
