# Generated by Django 4.2.1 on 2023-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='actual_01_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_02_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_03_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_04_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_05_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='target',
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
    ]
