# Generated by Django 4.2.1 on 2023-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_mng', '0002_kpi_actual_01_23_kpi_actual_02_23_kpi_actual_03_23_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='actual_06_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_07_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_08_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_09_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_10_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_11_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_12_23',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
