# Generated by Django 4.2.1 on 2023-08-04 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_mng', '0003_kpi_actual_06_23_kpi_actual_07_23_kpi_actual_08_23_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(max_length=99, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target',
            field=models.CharField(max_length=99, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
