# Generated by Django 4.2.1 on 2023-07-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics_mng', '0002_characteristic_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DefectCatalogueToCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics_mng.characteristic')),
                ('defect_catalogue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defect_cat_mng.defectcatalogue')),
            ],
        ),
        migrations.AddField(
            model_name='defectcatalogue',
            name='characteristics',
            field=models.ManyToManyField(blank=True, related_name='characteristics', through='defect_cat_mng.DefectCatalogueToCharacteristics', to='characteristics_mng.characteristic'),
        ),
    ]
