# Generated by Django 4.2.1 on 2023-06-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dox_mng', '0013_alter_document_type_alter_documenteditpurgatory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InteractionToDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dox_mng.document')),
                ('interaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction_mng.interaction')),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='documents',
            field=models.ManyToManyField(blank=True, through='interaction_mng.InteractionToDocuments', to='dox_mng.document'),
        ),
    ]
