# Generated by Django 4.2.1 on 2023-06-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0003_process_kpis_process_opportunities_process_risks'),
        ('interaction_mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='from_process_step',
            field=models.ForeignKey(db_column='from_process_step_name', default=1, on_delete=django.db.models.deletion.CASCADE, to='process_mng.processstep', to_field='name'),
            preserve_default=False,
        ),
    ]
