# Generated by Django 4.2.1 on 2023-06-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0003_process_kpis_process_opportunities_process_risks'),
        ('interaction_mng', '0002_interaction_from_process_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='to_process_step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_process_step', to='process_mng.processstep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='from_process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_process_step', to='process_mng.processstep'),
        ),
    ]
