# Generated by Django 4.2.1 on 2023-06-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0003_process_kpis_process_opportunities_process_risks'),
        ('interaction_mng', '0003_interaction_to_process_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='from_process_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_process_step', to='process_mng.processstep'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='to_process_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_process_step', to='process_mng.processstep'),
        ),
    ]
