# Generated by Django 4.2.1 on 2023-07-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0004_alter_process_process_owner_and_more'),
        ('interaction_mng', '0004_alter_interaction_from_process_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='from_process_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_process_step', to='process_mng.processstep'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='to_process_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_process_step', to='process_mng.processstep'),
        ),
    ]
