# Generated by Django 4.2.1 on 2023-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('inventory_number', models.CharField(blank=True, max_length=99, null=True)),
                ('characteristics', models.TextField(blank=True, null=True)),
                ('installation_date', models.DateField()),
                ('calibration_interval_in_days', models.IntegerField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
