# Generated by Django 4.2.1 on 2023-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringequipment',
            name='calibration_interval_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measuringequipment',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
