# Generated by Django 4.2.1 on 2023-08-04 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_mng', '0002_alter_measuringequipment_calibration_interval_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringequipment',
            name='name',
            field=models.CharField(max_length=99, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
