# Generated by Django 4.2.1 on 2024-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_mng', '0002_alter_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=99, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
