# Generated by Django 4.2.1 on 2023-06-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_mng', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Risk',
            new_name='Opportunity',
        ),
    ]
