# Generated by Django 4.2.1 on 2023-06-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_mng', '0002_rename_risk_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
