# Generated by Django 4.2.1 on 2023-06-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newactions_mng', '0001_initial'),
        ('opportunity_mng', '0003_opportunity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitiesToActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newactions_mng.newaction')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity_mng.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='long_term_action',
            field=models.ManyToManyField(blank=True, through='opportunity_mng.OpportunitiesToActions', to='newactions_mng.newaction'),
        ),
    ]
