# Generated by Django 4.2.1 on 2023-06-29 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics_mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
