# Generated by Django 4.2.1 on 2023-06-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_plan_mng', '0002_processcontrolplanstep_processcontrolplan_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcontrolplanstep',
            name='requirements',
        ),
    ]
