# Generated by Django 4.2.1 on 2023-06-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_plan_mng', '0003_remove_processcontrolplanstep_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processcontrolplanstep',
            old_name='process_characteristics',
            new_name='characteristics',
        ),
        migrations.RemoveField(
            model_name='processcontrolplanstep',
            name='product_characteristics',
        ),
    ]
