# Generated by Django 4.2.1 on 2023-06-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics_mng', '0002_characteristic_attachment'),
        ('control_plan_mng', '0004_rename_process_characteristics_processcontrolplanstep_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcontrolplanstep',
            name='characteristics',
        ),
        migrations.CreateModel(
            name='ProcessControlPlanStepToCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics_mng.characteristic')),
                ('process_control_plan_step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_plan_mng.processcontrolplanstep')),
            ],
        ),
        migrations.AddField(
            model_name='processcontrolplanstep',
            name='characteristics',
            field=models.ManyToManyField(blank=True, related_name='characteristic', through='control_plan_mng.ProcessControlPlanStepToCharacteristic', to='characteristics_mng.characteristic'),
        ),
    ]
