# Generated by Django 4.2.1 on 2023-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plan_mng', '0006_processcontrolplantoprocesscontrolplanstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcontrolplan',
            name='name',
            field=models.CharField(max_length=99, unique=True),
        ),
    ]
