# Generated by Django 4.2.1 on 2023-06-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0001_initial'),
        ('control_plan_mng', '0007_alter_processcontrolplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcontrolplan',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee'),
        ),
    ]
