# Generated by Django 4.2.1 on 2023-07-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0002_alter_accesslevels_description_and_more'),
        ('control_plan_mng', '0008_alter_processcontrolplan_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcontrolplan',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mng.employee'),
        ),
    ]
