# Generated by Django 4.2.1 on 2024-02-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_analysis_machines_remove_analysis_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='additional_expense_machines_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='additional_expense_materials_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='additional_expense_positions_total',
        ),
    ]
