# Generated by Django 4.2.1 on 2024-02-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_analysis_additional_expense_machines_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='total_additional_costs',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='total_costs',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='total_direct_costs',
        ),
    ]
