# Generated by Django 4.2.1 on 2024-02-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_analysis_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='machine1_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='machine2_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='machine3_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='machine4_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='machine5_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='material1_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='material2_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='material3_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='material4_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='material5_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='position1_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='position2_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='position3_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='position4_total',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='position5_total',
        ),
    ]
