# Generated by Django 4.1.4 on 2023-01-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('identification', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('Quality Manager', 'Quality Manager'), ('Quality Engineer', 'Quality Engineer'), ('Quality Inspector', 'Quality Inspector')], max_length=30)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
