# Generated by Django 4.1.4 on 2023-01-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=30)),
                ('starting_date', models.CharField(max_length=30)),
                ('date_last_hse_training', models.CharField(max_length=30)),
                ('date_next_hse_training', models.CharField(max_length=30)),
                ('egn', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('identification', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PositionsToAccessLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_mng.accesslevels')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_mng.positions')),
            ],
        ),
        migrations.AddField(
            model_name='positions',
            name='access_levels',
            field=models.ManyToManyField(blank=True, through='hr_mng.PositionsToAccessLevels', to='hr_mng.accesslevels'),
        ),
        migrations.AddField(
            model_name='positions',
            name='access_rights',
            field=models.ForeignKey(db_column='access_right_type', on_delete=django.db.models.deletion.CASCADE, to='hr_mng.accessrights', to_field='type'),
        ),
        migrations.CreateModel(
            name='EmployeeToTrainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_mng.trainings')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(db_column='position_code', on_delete=django.db.models.deletion.CASCADE, to='hr_mng.positions', to_field='code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='trainings',
            field=models.ManyToManyField(blank=True, through='hr_mng.EmployeeToTrainings', to='hr_mng.trainings'),
        ),
    ]
