# Generated by Django 4.2.1 on 2023-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevels',
            name='description',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='accessrights',
            name='description',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='accessrights',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='name',
            field=models.CharField(max_length=99),
        ),
    ]
