# Generated by Django 4.2.1 on 2023-07-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0002_alter_accesslevels_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(db_column='position_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mng.positions', to_field='code'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='access_rights',
            field=models.ForeignKey(db_column='access_right_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mng.accessrights', to_field='type'),
        ),
    ]
