# Generated by Django 4.1.4 on 2023-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0002_alter_employee_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
