# Generated by Django 4.1.4 on 2023-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0004_alter_employee_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='starting_date',
            field=models.CharField(max_length=30),
        ),
    ]
