# Generated by Django 4.2.1 on 2024-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0004_alter_employee_contract_number_alter_employee_egn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
