# Generated by Django 4.1.4 on 2023-01-06 13:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('owner', models.CharField(max_length=30)),
                ('attachment', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
