# Generated by Django 4.1.4 on 2023-03-05 09:10

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEditPurgatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('revision', models.PositiveIntegerField()),
                ('creation_date', models.CharField(max_length=30)),
                ('revision_date', models.CharField(max_length=30)),
                ('revision_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], max_length=30)),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(db_column='owner_ident', on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee', to_field='identification')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('revision_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], max_length=30)),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(db_column='owner_ident', on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee', to_field='identification')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
