# Generated by Django 4.1.4 on 2023-03-05 12:53

import cloudinary.models
from django.db import migrations
import erp_demo.main_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[erp_demo.main_app.custom_validators.validate_file_size], verbose_name='file'),
        ),
    ]
