# Generated by Django 4.1.4 on 2023-03-05 12:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0002_alter_document_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
