# Generated by Django 4.1.4 on 2023-01-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0005_alter_employee_starting_date'),
        ('dox_mng', '0002_document_creation_date_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(db_column='owner_ident', on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee', to_field='identification'),
        ),
    ]
