# Generated by Django 4.1.4 on 2023-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0002_documenteditpurgatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
