# Generated by Django 4.1.4 on 2023-03-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0003_alter_document_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='dox_mng.document')),
            ],
        ),
    ]
