# Generated by Django 4.1.4 on 2023-01-04 13:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0003_alter_document_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
