# Generated by Django 4.1.4 on 2023-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0004_documentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenteditpurgatory',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
