# Generated by Django 4.1.4 on 2023-01-06 06:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0004_alter_document_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
