# Generated by Django 4.1.4 on 2023-03-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0005_documenteditpurgatory_is_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenteditpurgatory',
            name='is_liked_by_user',
        ),
        migrations.AddField(
            model_name='document',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
