# Generated by Django 4.1.4 on 2023-03-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0006_remove_documenteditpurgatory_is_liked_by_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentLike',
        ),
    ]
