# Generated by Django 4.1.4 on 2023-01-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0006_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=30),
        ),
    ]
