# Generated by Django 4.1.4 on 2023-04-28 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dox_mng', '0007_delete_documentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_liked_by_user',
        ),
        migrations.CreateModel(
            name='DocumentLikesToUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dox_mng.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='likes',
            field=models.ManyToManyField(blank=True, through='dox_mng.DocumentLikesToUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
