# Generated by Django 4.1.4 on 2023-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0008_remove_document_is_liked_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
