# Generated by Django 4.1.4 on 2023-04-28 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dox_mng', '0009_document_is_liked_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlikestousers',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dox_mng.document'),
        ),
        migrations.AlterField(
            model_name='documentlikestousers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
