# Generated by Django 4.1.4 on 2023-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0011_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='status',
            field=models.CharField(choices=[('Latest rev', 'Latest rev'), ('Under rev', 'Under rev')], max_length=30),
        ),
    ]
