# Generated by Django 4.2.1 on 2023-06-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0012_alter_documenteditpurgatory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('External', 'External'), ('Policy', 'Policy'), ('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='type',
            field=models.CharField(choices=[('External', 'External'), ('Policy', 'Policy'), ('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=30),
        ),
    ]
