# Generated by Django 4.2.1 on 2023-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox_mng', '0013_alter_document_type_alter_documenteditpurgatory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Latest rev', 'Latest rev'), ('Under rev', 'Under rev')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('External', 'External'), ('Policy', 'Policy'), ('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='creation_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='revision_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='status',
            field=models.CharField(choices=[('Latest rev', 'Latest rev'), ('Under rev', 'Under rev')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='type',
            field=models.CharField(choices=[('External', 'External'), ('Policy', 'Policy'), ('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Instruction', 'Instruction'), ('Form', 'Form')], max_length=50),
        ),
    ]
