# Generated by Django 4.2.1 on 2023-07-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0002_alter_accesslevels_description_and_more'),
        ('dox_mng', '0015_alter_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenteditpurgatory',
            name='owner',
            field=models.ForeignKey(db_column='owner_ident', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mng.employee', to_field='identification'),
        ),
    ]
