# Generated by Django 4.2.1 on 2023-06-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions_mng', '0003_alter_action_type'),
        ('risk_mng', '0002_risk_description_risk_ia_test_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='long_term_action',
        ),
        migrations.CreateModel(
            name='RisksToActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions_mng.action')),
                ('risk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_mng.risk')),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='long_term_action',
            field=models.ManyToManyField(blank=True, through='risk_mng.RisksToActions', to='actions_mng.action'),
        ),
    ]
