# Generated by Django 4.2.1 on 2023-08-04 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_mng', '0004_alter_risk_long_term_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=99, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
