# Generated by Django 4.2.1 on 2023-07-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('grinding', models.PositiveIntegerField(blank=True, null=True)),
                ('welding', models.PositiveIntegerField(blank=True, null=True)),
                ('blasting', models.PositiveIntegerField(blank=True, null=True)),
                ('painting', models.PositiveIntegerField(blank=True, null=True)),
                ('assembly', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
