# Generated by Django 4.2.1 on 2023-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_mng', '0002_remove_statmodel1_name_statmodel1_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statmodel1',
            name='total_pieces',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
