# Generated by Django 4.2.1 on 2023-07-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_mng', '0003_statmodel1_total_pieces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statmodel1',
            old_name='number',
            new_name='name',
        ),
    ]
