# Generated by Django 4.2.1 on 2023-07-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreview',
            name='kpis_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='nonconformities_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='opportunities_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='resources_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='risks_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='suppliers_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
