# Generated by Django 4.1.4 on 2023-04-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mng', '0003_alter_customer_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='customer',
            name='correspondence_address',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mol',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('', 'Физическо лице'), ('Company', 'Юридическо лице'), ('Institution', 'Институция')], max_length=30),
        ),
    ]
