# Generated by Django 4.1.4 on 2023-04-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mng', '0004_alter_customer_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_person',
            new_name='contact_person1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='correspondence_address',
            new_name='correspondence_address1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mol',
            new_name='mol1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person2',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person3',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person4',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person5',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='correspondence_address2',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='correspondence_address3',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='correspondence_address4',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='correspondence_address5',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email5',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mol2',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mol3',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mol4',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mol5',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('', 'Празно'), ('Физическо лице', 'Физическо лице'), ('Юридическо лице', 'Юридическо лице'), ('Институция', 'Институция')], max_length=30),
        ),
    ]
