# Generated by Django 4.1.4 on 2023-04-17 09:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mng', '0005_rename_contact_person_customer_contact_person1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
