# Generated by Django 4.1.4 on 2023-04-17 10:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mng', '0006_customer_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
