# Generated by Django 4.2.1 on 2023-06-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mng', '0009_customer_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('', 'Empty'), ('Физическо лице', 'Individual'), ('Юридическо лице', 'Legal entity'), ('Институция', 'Institution')], max_length=30),
        ),
    ]
