# Generated by Django 4.2.1 on 2023-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mng', '0010_alter_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('', 'Empty'), ('Физическо лице', 'Individual'), ('Юридическо лице', 'Legal entity'), ('Институция', 'Institution')], max_length=50),
        ),
    ]
