# Generated by Django 4.2.1 on 2023-06-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0001_initial'),
        ('resource_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesAssignedToEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_mng.resource')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('resource', 'employee')},
            },
        ),
    ]
