# Generated by Django 4.2.1 on 2023-06-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0003_process_kpis_process_opportunities_process_risks'),
        ('resource_mng', '0002_resourcesassignedtoemployees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesAssignedToProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_mng.process')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_mng.resource')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('resource', 'process')},
            },
        ),
    ]
