# Generated by Django 4.2.1 on 2023-06-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_mng', '0001_initial'),
        ('customer_mng', '0010_alter_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonconformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_claim_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_claim_date', models.DateField(blank=True, null=True)),
                ('internal_claim_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nonconformity_start_date', models.DateField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_revision', models.CharField(blank=True, max_length=50, null=True)),
                ('part_name', models.CharField(blank=True, max_length=99, null=True)),
                ('customer_definition', models.TextField(blank=True, null=True)),
                ('internal_definition', models.TextField(blank=True, null=True)),
                ('team_members', models.TextField(blank=True, null=True)),
                ('containment_actions', models.TextField(blank=True, null=True)),
                ('correction_actions', models.TextField(blank=True, null=True)),
                ('possible_root_cause1', models.CharField(blank=True, max_length=99, null=True)),
                ('cause1_ask_why1', models.CharField(blank=True, max_length=99, null=True)),
                ('cause1_ask_why2', models.CharField(blank=True, max_length=99, null=True)),
                ('cause1_ask_why3', models.CharField(blank=True, max_length=99, null=True)),
                ('cause1_ask_why4', models.CharField(blank=True, max_length=99, null=True)),
                ('cause1_ask_why5', models.CharField(blank=True, max_length=99, null=True)),
                ('possible_root_cause2', models.CharField(blank=True, max_length=99, null=True)),
                ('cause2_ask_why1', models.CharField(blank=True, max_length=99, null=True)),
                ('cause2_ask_why2', models.CharField(blank=True, max_length=99, null=True)),
                ('cause2_ask_why3', models.CharField(blank=True, max_length=99, null=True)),
                ('cause2_ask_why4', models.CharField(blank=True, max_length=99, null=True)),
                ('cause2_ask_why5', models.CharField(blank=True, max_length=99, null=True)),
                ('possible_root_cause3', models.CharField(blank=True, max_length=99, null=True)),
                ('cause3_ask_why1', models.CharField(blank=True, max_length=99, null=True)),
                ('cause3_ask_why2', models.CharField(blank=True, max_length=99, null=True)),
                ('cause3_ask_why3', models.CharField(blank=True, max_length=99, null=True)),
                ('cause3_ask_why4', models.CharField(blank=True, max_length=99, null=True)),
                ('cause3_ask_why5', models.CharField(blank=True, max_length=99, null=True)),
                ('possible_root_cause4', models.CharField(blank=True, max_length=99, null=True)),
                ('cause4_ask_why1', models.CharField(blank=True, max_length=99, null=True)),
                ('cause4_ask_why2', models.CharField(blank=True, max_length=99, null=True)),
                ('cause4_ask_why3', models.CharField(blank=True, max_length=99, null=True)),
                ('cause4_ask_why4', models.CharField(blank=True, max_length=99, null=True)),
                ('cause4_ask_why5', models.CharField(blank=True, max_length=99, null=True)),
                ('possible_root_cause5', models.CharField(blank=True, max_length=99, null=True)),
                ('cause5_ask_why1', models.CharField(blank=True, max_length=99, null=True)),
                ('cause5_ask_why2', models.CharField(blank=True, max_length=99, null=True)),
                ('cause5_ask_why3', models.CharField(blank=True, max_length=99, null=True)),
                ('cause5_ask_why4', models.CharField(blank=True, max_length=99, null=True)),
                ('cause5_ask_why5', models.CharField(blank=True, max_length=99, null=True)),
                ('permanent_corrective_actions', models.TextField(blank=True, null=True)),
                ('breakpoint_batch_number', models.CharField(blank=True, max_length=99, null=True)),
                ('breakpoint_at_customer_date', models.DateField(blank=True, null=True)),
                ('systematic_actions', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_mng.customer')),
                ('nonconformity_owner', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
