# Generated by Django 4.2.1 on 2023-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity_mng', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonconformity',
            old_name='customer_definition',
            new_name='name',
        ),
    ]
