# Generated by Django 4.2.1 on 2023-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity_mng', '0002_rename_customer_definition_nonconformity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformity',
            name='name',
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
    ]
