# Generated by Django 4.2.1 on 2023-06-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newactions_mng', '0001_initial'),
        ('nonconformity_mng', '0003_alter_nonconformity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonconformity',
            name='containment_actions',
        ),
        migrations.RemoveField(
            model_name='nonconformity',
            name='correction_actions',
        ),
        migrations.RemoveField(
            model_name='nonconformity',
            name='permanent_corrective_actions',
        ),
        migrations.CreateModel(
            name='PermanentToActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newactions_mng.newaction')),
                ('nonconformity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity_mng.nonconformity')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionToActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newactions_mng.newaction')),
                ('nonconformity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity_mng.nonconformity')),
            ],
        ),
        migrations.CreateModel(
            name='ContainmentToActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newactions_mng.newaction')),
                ('nonconformity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity_mng.nonconformity')),
            ],
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='containment_actions',
            field=models.ManyToManyField(blank=True, related_name='containment_actions', through='nonconformity_mng.ContainmentToActions', to='newactions_mng.newaction'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='correction_actions',
            field=models.ManyToManyField(blank=True, related_name='correction_actions', through='nonconformity_mng.CorrectionToActions', to='newactions_mng.newaction'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='permanent_corrective_actions',
            field=models.ManyToManyField(blank=True, related_name='permanent_corrective_actions', through='nonconformity_mng.PermanentToActions', to='newactions_mng.newaction'),
        ),
    ]
