# Generated by Django 4.2.1 on 2023-06-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newactions_mng', '0001_initial'),
        ('nonconformity_mng', '0004_remove_nonconformity_containment_actions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonconformity',
            name='systematic_actions',
        ),
        migrations.CreateModel(
            name='SystematicToActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newactions_mng.newaction')),
                ('nonconformity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity_mng.nonconformity')),
            ],
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='systematic_actions',
            field=models.ManyToManyField(blank=True, related_name='systematic_actions', through='nonconformity_mng.SystematicToActions', to='newactions_mng.newaction'),
        ),
    ]
