# Generated by Django 4.2.1 on 2023-07-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mng', '0011_alter_customer_type'),
        ('hr_mng', '0003_alter_employee_position_and_more'),
        ('nonconformity_mng', '0005_remove_nonconformity_systematic_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformity',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_mng.customer'),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='nonconformity_owner',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mng.employee'),
        ),
    ]
