# Generated by Django 4.2.1 on 2023-08-04 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity_mng', '0006_alter_nonconformity_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformity',
            name='name',
            field=models.CharField(max_length=99, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
