# Generated by Django 4.1.4 on 2023-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('eik', models.PositiveIntegerField(max_length=20)),
                ('mol', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('manager_name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
