# Generated by Django 4.1.4 on 2023-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='eik',
            field=models.PositiveIntegerField(),
        ),
    ]
