# Generated by Django 4.1.4 on 2023-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_mng', '0002_alter_organization_eik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=99, unique=True),
        ),
    ]
