# Generated by Django 4.1.4 on 2023-02-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=30)),
                ('performed_at_time', models.CharField(max_length=30)),
                ('execution_time', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
