# Generated by Django 4.1.4 on 2023-03-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=297)),
                ('performed_at_time', models.CharField(max_length=30)),
                ('execution_time', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=99)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=30)),
                ('external_document', models.CharField(max_length=30)),
                ('clause', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementToProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_mng.processstep')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.requirements')),
            ],
        ),
        migrations.AddField(
            model_name='requirements',
            name='covered_by_process_step',
            field=models.ManyToManyField(blank=True, through='main_app.RequirementToProcessStep', to='process_mng.processstep'),
        ),
    ]
