# Generated by Django 4.1.4 on 2023-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainslog',
            name='performed_at_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
