# Generated by Django 4.1.4 on 2023-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainslog',
            name='operation',
            field=models.CharField(max_length=90),
        ),
    ]
