# Generated by Django 4.2.1 on 2023-06-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_captainslog_performed_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='clause_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
