# Generated by Django 4.1.4 on 2023-02-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_captainslog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainslog',
            name='operation',
            field=models.CharField(max_length=297),
        ),
    ]
