# Generated by Django 4.2.1 on 2023-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_requirements_clause_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='clause_name',
            field=models.CharField(max_length=99),
        ),
    ]
