# Generated by Django 4.1.4 on 2023-02-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0004_process_slug'),
        ('main_app', '0004_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementToProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_mng.processstep')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.requirements')),
            ],
        ),
    ]
