# Generated by Django 4.1.4 on 2023-02-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_mng', '0004_process_slug'),
        ('main_app', '0005_requirementtoprocessstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='covered_by_process_step',
            field=models.ManyToManyField(blank=True, through='main_app.RequirementToProcessStep', to='process_mng.processstep'),
        ),
    ]
