# Generated by Django 4.2.1 on 2023-06-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Containment', 'Containment'), ('Correction', 'Correction'), ('Corrective Action', 'Corrective Action'), ('Systematic Action', 'Systematic Action'), ('Improvement', 'Improvement'), ('Task', 'task')], max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('target_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Defined', 'Not Defined'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('responsible', models.ForeignKey(db_column='owner_ident', on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee', to_field='identification')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
