# Generated by Django 4.2.1 on 2023-06-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_mng', '0001_initial'),
        ('newactions_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('owner', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('scope', models.CharField(blank=True, max_length=99, null=True)),
                ('name', models.CharField(max_length=99, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlanStepToActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newactions_mng.newaction')),
                ('action_plan_step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actionplan_mng.actionplanstep')),
            ],
        ),
        migrations.AddField(
            model_name='actionplanstep',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='actions', through='actionplan_mng.ActionPlanStepToActions', to='newactions_mng.newaction'),
        ),
        migrations.AddField(
            model_name='actionplanstep',
            name='parent_action_plan',
            field=models.ForeignKey(db_column='parent_action_plan_name', on_delete=django.db.models.deletion.CASCADE, to='actionplan_mng.actionplan', to_field='name'),
        ),
    ]
