# Generated by Django 4.2.1 on 2023-07-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mng', '0001_initial'),
        ('actionplan_mng', '0002_alter_actionplanstep_parent_action_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_mng.employee'),
        ),
    ]
